# Generated by Django 5.1.7 on 2025-03-12 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer',
            name='location_icon',
            field=models.ImageField(blank=True, null=True, upload_to='images/location/'),
        ),
    ]
