# Generated by Django 5.1.7 on 2025-03-12 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_remove_contactuspage_contact_form_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactuspage',
            name='header',
        ),
        migrations.DeleteModel(
            name='Header',
        ),
    ]
