# Generated by Django 5.1.7 on 2025-03-12 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_remove_contactuspage_header_delete_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedialink',
            name='icon',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
