# Generated by Django 5.1.7 on 2025-03-12 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_alter_socialmedialink_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedialink',
            name='icon',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
