# Generated by Django 5.1.7 on 2025-03-12 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_card_testimonial_landingpage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='description',
            new_name='card_content',
        ),
    ]
