# Generated by Django 5.1.7 on 2025-03-16 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_remove_landingpage_card_remove_landingpage_footer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='card',
            field=models.ManyToManyField(related_name='card', to='cms.card'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='testimonial',
            field=models.ManyToManyField(related_name='testimonial', to='cms.testimonial'),
        ),
    ]
