# Generated by Django 5.1.7 on 2025-03-16 07:52

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0013_alter_socialmedialink_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactuspage',
            name='background_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='background_image'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='location_icon',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='location_icon'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='background_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='background_image'),
        ),
    ]
